---
abstract: 'Asynchronous Lingr client.'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  CPAN::Meta: 0
  ExtUtils::MakeMaker: 6.36
dynamic_config: 0
generated_by: 'Module::Install version 1.06, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Lingr
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  JSON: 0
  Log::Minimal: 0
  Try::Tiny: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
